### ISSUE TITLE
error when trying to open the existing project

### ISSUE THREAD

**Issue by YUDHPK** [googlecodelabs/android-n-quick-settings#3]
<code>Error:Cause: failed to find target with hash string 'android-N' in: C:\Users\PRAFUL\AppData\Local\Android\Sdk
<a href="install.android.platform">Install missing platform(s) and sync project</a></code>

i followed proper instructions given on the below link
https://codelabs.developers.google.com/codelabs/android-n-quick-settings/index.html?index=..%2F..%2Findex#2

![image](https://cloud.githubusercontent.com/assets/16633152/20454589/19c2c9c6-ae6b-11e6-8a51-6f1b1a4bdf64.png)

**Comment by AndroidDeveloperLB** [comment]
Change it to:

```
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.google.android_quick_settings"
        minSdkVersion 24
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
```

Also, in the other gradle file , change to :

`       classpath 'com.android.tools.build:gradle:2.3.0-beta1'`
