### ISSUE TITLE
Cannot import correctly

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlecodelabs/android-n-quick-settings#5]
I get this error:

> Error:Unable to find method 'org.gradle.api.tasks.Sync.getInputs()Lorg/gradle/api/internal/TaskInputsInternal;'.
> Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> <a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> <a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

How come?

**Comment by ngzhian** [comment]
Hi @AndroidDeveloperLB , did you the steps suggested in the error, such as "closing the IDE and then killing all Java processes."?

**Comment by AndroidDeveloperLB** [comment]
Yes.

**Comment by ngzhian** [comment]
Can you pull from master and try again? I have merged something that fixed other issues, maybe that will resolve this too.

**Comment by AndroidDeveloperLB** [comment]
I have now, and it can't use the latest gradle version (classpath 'com.android.tools.build:gradle:3.0.0-alpha8') , only latest stable one (2.3.3) . 
The sample works fine. Allows to put tiles in the quick-settings.

Can you please add description to the repo? Maybe screenshots?

**Comment by ngzhian** [comment]
I'll stick to version recommended on the [official docs](https://developer.android.com/studio/releases/gradle-plugin.html).
I have also added a link to the codelab in the README, the description for the project is available there, which describes the project with screenshots.
If this builds for you please close this issue, thank you! :)

**Comment by AndroidDeveloperLB** [comment]
I meant screenshots of the sample

**Comment by ngzhian** [comment]
There's a screenshot of a sample on the codelab website.

**Comment by AndroidDeveloperLB** [comment]
Not the same.
Compare this:
![image](https://user-images.githubusercontent.com/5357526/28898095-ae51b30e-77ec-11e7-81c4-f92c633054fc.png)
With this:
![maxthonsnap20170803020347](https://user-images.githubusercontent.com/5357526/28898715-23dc1ecc-77f0-11e7-8488-90fdc766f047.png)

Also, it's recommended to put description inside the repo. Not just links...

**Comment by ngzhian** [comment]
If you're okay with using the image you provided, I'll add it to the README! :)

**Comment by AndroidDeveloperLB** [comment]
Decided to create a PR of a gif animation instead:
https://github.com/googlecodelabs/android-n-quick-settings/pull/8
