### ISSUE TITLE
Error in example code: Quick Settings

### ISSUE THREAD

**Issue by MustafaTaj** [googlecodelabs/android-n-quick-settings#9]
![google error](https://user-images.githubusercontent.com/19856492/40880438-0cd4360a-66b1-11e8-9373-1a0f897a6f90.png)
Hello google team,
you have an error in your example code

- Android N: Quick Settings
      - 6. Launch an activity from a tile
           Second code example
               "intent.addFlag.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);"
               Should be replaced by 
               "intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);"

find the attached photo

error can be found in:
https://codelabs.developers.google.com/codelabs/android-n-quick-settings/index.html?index=..%2F..%2Findex#5

Regards

**Comment by pfmaggi** [comment]
This codelab has been deprecated.
